### ISSUE TITLE
The user has to start the report again if they cancel at summary page

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1925] opened 2020-05-15 18:26 UTC
## Summary

As a fix in PR#1908.  If the user cancels the report in the middle way and use the back arrow key to go back to the previous pages, it will force the user to fill the report again and start at the your privacy page . ---> That's good

But it is not applied for summary page. If the user cancels at summary page and use arrow key to go back, it will take the user to summary page instead of your privacy page.  All of info on summary page is cleared but the submit button is enabled (At this time, the user can submit the empty report without consent). The your privacy will be appeared only if the user press Edit button first time on any page ...The user has to re-enter the info by clicking on edit button on each pages (to go back and forth )

I think it will be better to apply the same flow as the other pages to avoid the confusion. If the user cancel at summary page, it will take the user to your privacy page and the user has to start the report from there.

## Steps to reproduce

> How exactly can the bug be reproduced? Be very specific.

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by lmcbhvu** [comment] 2020-05-15 18:29
**Conversation from Slack:**
Norm:
Hi Hong. I agree that sounds a bit buggy. If they cancel on the summary page they should need to restart the flow and not be able to submit an empty report

**Comment by DianeLiu2019** [comment] 2020-05-27 13:54
The issue is fixed in PR#1944

**Closed by DianeLiu2019** 2020-05-27 13:54 UTC
Labels: bug, medium priority
