### ISSUE TITLE
choosing "other  " in how did it start page, didn't show "other" in confirmation page  -bug

### ISSUE THREAD

**Issue by DianeLiu2019** [cds-snc/report-a-cybercrime#1490] opened 2020-02-20 18:29 UTC
## Summary

choosing "other  " in how did it start page, didn't show "other" in confirmation page 
 

## Steps to reproduce

1. Go to How did it start page, choose checkbox "other" for how did the suspect reach you.
2. go through to confirmation page. "other" option didn't show in the confirmation page.

**Comment by sastels** [comment] 2020-02-21 20:47
duplicate of #1452

**Closed by sastels** 2020-02-21 20:47 UTC
Labels: bug, need for launch
