### ISSUE TITLE
Click to call links for CAFC number in app 

### ISSUE THREAD

**Issue by anikbrazeau** [cds-snc/report-a-cybercrime#1455] opened 2020-02-19 20:43 UTC
## Summary

Phone numbers appear on these pages:

- landing page
- thank you page
- privacy statement page

Consider creating links to phone number so that it's easier to call directly by clicking/selecting.

**Comment by DianeLiu2019** [comment] 2020-06-02 17:41
The issue is fixed by PR #1963

**Closed by DianeLiu2019** 2020-06-02 17:41 UTC
Labels: low priority
