### ISSUE TITLE
Warning message in Subject of analyst email should be French as well for french report

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#2226] opened 2020-08-19 13:17 UTC
## Summary

Warning message in Subject of analyst email should be French as well

## Steps to reproduce

1. Submit french report content some of harmful words or offensive picture

![page4 (1)](https://user-images.githubusercontent.com/60269104/90639526-c87f1000-e1fc-11ea-818c-cbf0ef43065b.jpg)

**Comment by dengcn** [comment] 2020-08-19 13:28
This bug is similar to another one I am working on, I will take this one to save team time

**Comment by ngosset** [comment] 2020-09-08 17:18
@dengcn Can you verify if this was fixed by your other PR? If it is we can close this Issue.

**Comment by dengcn** [comment] 2020-09-08 17:29
Norm:  This is duplicated PR, the same as PR2084, PR is in review not merged since Form Refactoring conflict. I will update the code when form refactoring is clean. Here is the old PR review link:Missing acute in french in self harm2084 by dengcn · Pull Request #2182 · cds-snc/report-a-cybercrime


| 
| 
| 
|  |  |

 |

 |
| 
|  | 
Missing acute in french in self harm2084 by dengcn · Pull Request #2182 ...

Fixes #2084 This is the fix to PR2084 Missing acute accent in self harm word section Description There are 2 iss...
 |

 |

 |




    On Tuesday, September 8, 2020, 01:18:42 p.m. EDT, ngosset <notifications@github.com> wrote:  
 
 


@dengcn Can you verify if this was fixed by your other PR? If it is we can close this Issue.

**Comment by dengcn** [comment] 2020-09-08 17:34
Norm: Just a correction, the issue is slightly different from that PR in review.  So I just label this as similar. we need to keep this PR, and I will handle this when refactoring is clean.

**Comment by dengcn** [comment] 2020-09-10 14:25
Hong, FYI there is another bug error in this scenario "WARNING: self harm words detected" in Email subject is also missing French, to avoid further similar PR in the same area, I will fix this as well.

**Closed** 2020-09-14 19:08 UTC
Labels: bug, low priority
