### ISSUE TITLE
Mess-up the file description if the offensive is included or not included in the report and in the database 

### ISSUE THREAD

**Issue by lmcbhvu** [cds-snc/report-a-cybercrime#1624] opened 2020-03-04 17:57 UTC
## Summary

Mess-up the file description if the offensive is included in the report

## Steps to reproduce

- launch the report and fill out the forms
- at supporting evidence page, attached offensive file first with description and the two other files with empty description
![file](https://user-images.githubusercontent.com/60269104/75908218-b4468280-5e17-11ea-810d-c9fda0a731d5.jpg)

## Unresolved questions

> Are there any related issues you consider out of scope for this issue that could be addressed in the future?

**Comment by lmcbhvu** [comment] 2020-03-10 02:59
Attached is one example in the database

![db](https://user-images.githubusercontent.com/60269104/76275385-8cad4b00-6259-11ea-85af-761dc6a72c20.jpg)

**Comment by lmcbhvu** [comment] 2020-03-10 15:18
Her is the reason why it is messed up. 
The file description is listed according the order of file loaded. If the file is loaded first, its description will be in the first item of File description array. 
The attached file is sorted according to the filename, not the order of file is loaded. 
When the report is created, it will combine the first sorted file with the first file description

In our example, I have 2 files. The file gun.jpg is loaded first and its description is gun. The file fruit.jpg is loaded next and its description is  fruit. In the file description array, it will list gun and then fruit. When it is displayed in the report and DB, it will combine and list file fruit with file description gun

**Comment by sastels** [comment] 2020-03-10 18:47
So I think when we changed the way we do files this got fixed (#1641, merged March 10). At least, I cannot reproduce this issue in the current master.

**Closed** 2020-03-17 17:17 UTC
Labels: bug, high priority
